### ISSUE TITLE
Problem with code not working outside of this project

### ISSUE THREAD

**Issue by sognatore99** [PaulKlinger/tinypc#1]
Paul I was able to get your code working using your provided project files. However I am having an issue trying to use the I2C code outside of your code.  I am using Atmel Studio vice MPLAB X (which is what I used to get your code to work).  I have create a project that only needs the LCD and I2C code.  I have attached if you don't mind looking it over.  I seem to be missing something very basic.  How does the project know to use PB0 and PB1 for the SDA and SDL lines?  When I step through the code it appears to be working.  Also I made sure that F_CPU 20000000 was set.  If you have the time I would appreciate a quick look.  I will continue to try to figure it out in the mean time.  Thanks in advance.

[OnlyI2C.zip](https://github.com/PaulKlinger/tinypc/files/3222072/OnlyI2C.zip)

**Comment by PaulKlinger** [comment]
I took a quick look at your project and I can't see anything obviously wrong in the code. Maybe there's some issue with the fuse configuration? I haven't used AtmelStudio yet, so I'm not sure how this works there. In the MPLAB X project the fuses are set in [device_config.c](https://github.com/PaulKlinger/tinypc/blob/master/code/mcc_generated_files/device_config.c)

The I2C peripheral (TWI0) uses PB0 and PB1 by default. Using the PORTMUX registers it's supposed to be possible to switch it to using PA1 & PA2, but that option seems to be missing from the datasheet.

**Comment by sognatore99** [comment]
Thanks for looking, I will look into the fuse configuration.  The I2C stuff is very frustrating, I switched from MPLAB to Atmel since I am more comfortable, but my expertise is not in C/C++.  Also thanks for uploading your great project it was a pleasure to look into!

**Comment by sognatore99** [comment]
So a follow up, I got it working.  I guess in my haste at 3:00am when I was attempting to create a "simple_i2c_fgras78.h" file I must have copied and pasted code to the simple_i2c_fgras78.c file something like this "void TWI_init();uint8_t TWI_start(uint8_t deviceAddr)" the compiler did not complain!  I am a C# guy so this stuff always kicks me where it hurts!  Again thanks for a great post and taking a look at my code.

**Comment by PaulKlinger** [comment]
Great! It's always nice to know that my projects are useful for someone :)

That was a weird problem though, I actually saw that and tried compiling this:

```
#include <stdio.h>
void test2() {
        printf("\ntest2\n");
}
void test2();int main() {
        printf("test");
        test2();
}
```

and it worked normally; sorry I didn't mention it. Maybe it has something to do with the function also being declared in the header file (I don't really know much about C either).
